### ISSUE TITLE
add current CPU temperature

### ISSUE THREAD

**Issue by martinpitt** [martinpitt/performance-graphs#25]
See design on https://garrett.github.io/cockpit-mockweb/metrics/current/

https://www.mjmwired.net/kernel/Documentation/thermal/sysfs-api.txt

e.g.
```
cat /sys/devices/virtual/thermal/thermal_zone0/temp 
61000
```
means 61 degrees Celsius.

**Comment by marusak** [comment]
https://github.com/cockpit-project/cockpit/issues/11364 FWIW

**Comment by garrett** [comment]
If we're only going to list CPU temp, we could integrate it in the card like this, perhaps:

![metrics-cpu-temp](https://user-images.githubusercontent.com/10246/92609468-e4834800-f2b6-11ea-83ed-b99c4fd11cee.png)

It might be weird at that height though. Perhaps it's better under the load. And perhaps it should say temperature.

(Sorry, working from an old mockup that doesn't reflect the current state of things... I just wanted to quickly throw something on this issue.)

**Comment by marusak** [comment]
Moved to https://github.com/cockpit-project/cockpit/issues/11364
