### ISSUE TITLE
inconsistent time formats

### ISSUE THREAD

**Issue by andreasn** [martinpitt/performance-graphs#3]
My VM is set to 12 hour clock.
While the headings in the page properly displays **4:00 PM**, **5:00 PM** etc. the individual events show the time as **04:12**, **02:31** etc.

02:31 means two in the morning in 24 hour clock, but I think this actually happened in the afternoon, ie. 2:30 PM.

![Screenshot from 2020-08-05 16-21-24](https://user-images.githubusercontent.com/209895/89424222-cebeb800-d737-11ea-9229-b40a6064e225.png)

**Comment by martinpitt** [comment]
Indeed it did, we need to render this consistently through locale-based  format. I wonder if we can get away with always using 24 hour format, though -- this AM/PM thing is so confusing, but then again I'm used to 24 hours..
