### ISSUE TITLE
history: jump to time

### ISSUE THREAD

**Issue by garrett** [martinpitt/performance-graphs#35]
## Default

We could have the page kind of look like this by default:

![metrics-time-jump-default](https://user-images.githubusercontent.com/10246/92609949-6e331580-f2b7-11ea-9cc7-5ce04278bcdf.png)

## Scrolling

Then, when you scroll, it would slide like such:

|||||
---|---|---|---
|![metrics-time-jump-default](https://user-images.githubusercontent.com/10246/92609949-6e331580-f2b7-11ea-9cc7-5ce04278bcdf.png)|![metrics-time-jump-scroll-2](https://user-images.githubusercontent.com/10246/92609948-6d9a7f00-f2b7-11ea-98f4-66f5c22b4214.png)|![metrics-time-jump-scroll-3](https://user-images.githubusercontent.com/10246/92609946-6d01e880-f2b7-11ea-8bf0-3474af91d5ee.png)|![metrics-time-jump-scroll-4](https://user-images.githubusercontent.com/10246/92609942-6c695200-f2b7-11ea-9f0d-3d00348cec0c.png)|

## Scrolled down, sticky header

That is, the metrics slides off and the header becomes sticky (with CSS `position: sticky; top: 0;`):

![metrics-time-jump-scroll-4](https://user-images.githubusercontent.com/10246/92609942-6c695200-f2b7-11ea-9f0d-3d00348cec0c.png)

**Comment by garrett** [comment]
I put the individual days in a card (they don't have shadows here) and put the jump to widget, as a dropdown, in the heading along with the column labels.

The expanded jump to would probably have something like a preset of the past few days at different time increments and a custom time that would bring up a date/time picker.

What do you think?

**Comment by andreasn** [comment]
Works fairly similar to the Logs page. I like it!
