### ISSUE TITLE
Better treat long mount points in Disks card?

### ISSUE THREAD

**Issue by martinpitt** [martinpitt/performance-graphs#42]
See what happens when they overflow. We'll need some clipping/tooltips.

**Comment by martinpitt** [comment]
Reproducer:

    dd if=/dev/zero of=/tmp/img bs=1M count=50 && mkfs -t ext3 /tmp/img && mkdir -p /mnt/this/is/some/reeeeeally/loooooong/mount/path && mount -o loop /tmp/img /mnt/this/is/some/reeeeeally/loooooong/mount/path && rm -f /tmp/img


This doesn't actually look too bad right now:

![image](https://user-images.githubusercontent.com/200109/93311305-21df5c80-f806-11ea-88e8-b697a4d00d7a.png)

Not sure if we desperately want to clip it or so. We should surely shorten the free/total string, though.

**Comment by marusak** [comment]
Moved to https://github.com/cockpit-project/cockpit/issues/14805
