### ISSUE TITLE
New data are "too spiky"

### ISSUE THREAD

**Issue by marusak** [martinpitt/performance-graphs#5]
When I leave the page opened for some time:
![Screenshot from 2020-08-10 14-49-31](https://user-images.githubusercontent.com/12330670/89784338-c93ae680-db18-11ea-8c54-e4cd2176ad62.png)

When I reload it then:
![Screenshot from 2020-08-10 14-50-41](https://user-images.githubusercontent.com/12330670/89784389-deb01080-db18-11ea-9484-d2bf19e4cf83.png)

It seems like every new data is recognized as spike?

**Comment by martinpitt** [comment]
The first screenshot is "not wrong" in the sense that there is a CPU drop and re-spike each and every minute, and in the  *middle* of a minute of all that. That really looks wrong, especially as the reload seems to much more sane. Do you still remember what kind of workload you had on that machine during this test? Or still have the PCP archives?

So there's two things here:

 * If we are getting too many spikes of a certain type within an hour (5?), clip them to only keep the 5 earliest (easy) or highest (more bookkeeping) .
 * There seems to be a bug with missing a few PCP frames when keeping the page refreshing -- the pattern is too regular to be a coincidence.

**Comment by martinpitt** [comment]
Ideas for my Monday self:
 * Have a little overlap to past data when retrieving fresh data, as otherwise the `rate` metrics will have a gap (first sample is always `false`)
 * Don't overwrite valid data with invalid false/null values
 * Ignore trailing null/false sequences (not sure if that actually happens) → best to keep track of the index of the last valid data in `this.most_recent`)

**Comment by martinpitt** [comment]
The above helped a bit. But Some graphs still look funny:

![image](https://user-images.githubusercontent.com/200109/92353256-2dcd6f00-f0e0-11ea-8571-2828b54cfb31.png)

This is because a `NaN` crept into the polygon:

```html
<polygon transform="matrix(-1,0,0,-1,1,11)" points="0,0 0.9076000000000001,0 0.9072,1 0.9074,2 0.9074,3 0.9054000000000001,4 0.908,5 0.9081999999999999,6 0.9081999999999999,7 0.9084,8 0.908,9 0.908,10 NaN,11 0,11"></polygon>
```

This is indeed because some samples have holes, see the use_cpu `null`s:

```json
[
    {   
        "use_cpu": [
            0.4,
            121.39999999999999,
            593.1999999999999
        ],
        "sat_cpu": 1.7400000095367432,
        "use_memory": [
            1124328,
            799100
        ],
        "sat_memory": 0,
        "use_disks": 1108.6000000000001,
        "use_network": 667125.2
    },  
    {   
        "use_cpu": [
            null,
            null,
            null
        ],
        "sat_cpu": 1.7400000095367432,
        "use_memory": [
            1124328,
            799100
        ],
        "use_network": 0
    },  
    {   
        "use_cpu": [
            0,
            121.2,
            594
        ],
        "sat_cpu": 1.7400000095367432,
        "use_memory": [
            1124328,
            799100
        ],
        "sat_memory": 0,
        "use_disks": 1108.4,
        "use_network": 667125
    }
]
```
