### ISSUE TITLE
Logic behind 'No data available between' is flawed

### ISSUE THREAD

**Issue by marusak** [martinpitt/performance-graphs#58]
I always see this banner even though there are such data and when I click on 'Load earlier data' they are loaded. Feels like there is the `+-1` issue.
![logiciswrong](https://user-images.githubusercontent.com/12330670/94248764-31098d00-ff1f-11ea-8240-b91a5e4cf5ea.png)

**Comment by martinpitt** [comment]
Thanks! Marking as release-blocker
