### ISSUE TITLE
CPU load is not properly normalized

### ISSUE THREAD

**Issue by marusak** [martinpitt/performance-graphs#6]
CPU load can easily get over 100% (due to more cores). Then graphs are misleading, as they show 100% and overflow (overflow is not visible though). Graph points should not get over 1, but they reach values as 2.5 and so.

![Screenshot from 2020-08-13 09-58-24](https://user-images.githubusercontent.com/12330670/90109213-c96ef800-dd4b-11ea-851b-b8bee319c6a9.png) 

![Screenshot from 2020-08-13 09-58-30](https://user-images.githubusercontent.com/12330670/90109203-c4aa4400-dd4b-11ea-9653-c114fecda924.png)

**Comment by marusak** [comment]
I __think__ that dividing `use_cpu` normalization with number of cores should do the trick.
```js
normalize: ([nice, user, sys]) => (nice + user + sys) / 1000 / cpus,
```

**Comment by martinpitt** [comment]
I can reproduce that in `vm-run -C 2`, thanks for spotting! I'll send a fix.
