### ISSUE TITLE
Duplicated events

### ISSUE THREAD

**Issue by martinpitt** [martinpitt/performance-graphs#81]
At 3:38 PM, "net i/o spike" is shown twice, and at 3:53 PM same for "disk i/o":

![image](https://user-images.githubusercontent.com/200109/95828410-3d6e5200-0d35-11eb-97f7-d19a50279cb7.png)

**Comment by martinpitt** [comment]
[/var/log/pcp/pmlogger](https://github.com/martinpitt/performance-graphs/files/5369629/pcp.zip) data to reproduce this. Select "Saturday, October 10" as the day.

**Comment by marusak** [comment]
Moved to https://github.com/cockpit-project/cockpit/issues/14809
